# Cole Weber
## Week 11 - 4/2/2021
### Python - Numpy Universal Functions

In [5]:
import numpy as np
arr1 = np.arange(1, 10)
arr2 = np.arange(11, 20)

z = []

for i, j in zip(arr1, arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [6]:
fname = ["Bob", "Frank", "James", "Natalie"]
lname = ["Jordan", "Brady", "Johnson", "Clark"]
flname = zip(fname, lname)
print(tuple(flname))

(('Bob', 'Jordan'), ('Frank', 'Brady'), ('James', 'Johnson'), ('Natalie', 'Clark'))


In [7]:
lst1 = [1, 2, 3, 4, 5]
lst2 = [10, 11, 12, 13, 14]
print(list(zip(lst1, lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [10]:
arr = np.arange(0, 21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [12]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [16]:
arr1 = np.random.randn(10)
arr2 = np.random.randn(10)
np.add(arr1, arr2)

array([ 0.14056512,  0.36015793,  4.51238342,  0.06469932, -1.20721285,
        0.12884855,  1.05510109, -0.06133521,  1.55669936,  0.41015496])

In [17]:
np.maximum(arr1, arr2)

array([0.3219026 , 1.30750825, 2.92213468, 0.52135904, 0.12274008,
       0.37688247, 1.4453336 , 0.24472554, 1.25191504, 0.47061294])

In [20]:
arr = np.arange(45).reshape(9,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [22]:
print(arr < 4)
print(np.where(arr < 4, 1,0))

[[ True  True  True  True False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[[1 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [23]:
print(np.where((arr < 4) & (arr > 2), 1, 0))

[[0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
