# Cole Weber
## Week 11 - 3/31/2021
### Python - Numpy Creating, Processing, and Transporting Arrays

In [1]:
import numpy as np

arr_2d = np.array([[1, 4, 5, 7, 8], [2, 6, 4, 5, 4]])

print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.dtype)

[[1 4 5 7 8]
 [2 6 4 5 4]]
2
(2, 5)
int32


In [2]:
# Can use zeros, ones, or empty
arr = np.zeros((2, 10))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [3]:
empty_arr = np.empty((2, 8), dtype = int)
print(empty_arr)

[[   0    0    0    0    0    0    0    0]
 [   0    0 1340    0    0    0    0    0]]


In [4]:
# arange
arr = np.arange(30)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [5]:
arr = np.arange(10, 30, 2)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[10 12 14 16 18 20 22 24 26 28]
(10,)
1
int32


In [6]:
arr = np.arange(1, 21)
print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)


In [7]:
# Reshape() splits the array into the given dimensions and elements. Can take 1-D to 2-D, 3-D, etc...
arr_2d = arr.reshape(4, 5)
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [8]:
arr_3d = arr.reshape(2, 2, 5)
print(arr_3d)
print(arr_3d.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
(2, 2, 5)


In [9]:
print(arr_3d.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [10]:
arr_3d = arr.reshape(2, 2, -1)
print(arr_3d)
print(arr_3d.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
(2, 2, 5)


In [11]:
#Flattening the array
arr_2d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
for num in arr:
    print(num)

1
2
3
4
5
6
7
8
9
10


In [14]:
print(arr_2d, "\n\n")
print(arr_3d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [15]:
for num in arr_2d:
    for n in num:
        print(n, "")

1 
2 
3 
4 
5 
6 
7 
8 
9 
10 
11 
12 
13 
14 
15 
16 
17 
18 
19 
20 


In [16]:
for number in arr_3d:
    for num in number:
        for n in num:
            print(n)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [17]:
for num in np.nditer(arr_3d):
    print(num)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [18]:
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [19]:
arr_2d[:,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20]])

In [20]:
for num in np.nditer(arr_2d[:,::2]):
    print(num)

1
3
5
6
8
10
11
13
15
16
18
20


In [21]:
for idx, num in np.ndenumerate(arr):
    print(idx, num)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10


In [22]:
arr_2d = np.arange(1, 9)
arr_2d = arr_2d.reshape(2, 4)
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
arr_2d * arr_2d

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [24]:
arr_2d + arr_2d

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [25]:
arr_2d ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)

In [26]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[1:6:2]

array([2, 4, 6])

In [28]:
arr[1:6:2] = 100

In [29]:
arr

array([  1, 100,   3, 100,   5, 100,   7,   8,   9,  10])

In [36]:
arr_2d = np.array([[2, 3, 5, 4], [6, 8, 2, 9], [1, 7, 3, 9]])
print(arr_2d.shape)
print(arr_2d[1][0])
print(arr_2d[1, 0])
print(arr_2d[:2,1:])

(3, 4)
6
6
[[3 5 4]
 [8 2 9]]


In [41]:
arr = np.zeros((9,9))
print(arr)
print(arr.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(9, 9)


In [44]:
print(arr.shape[0])
print(arr.shape[1])

9
9


In [47]:
l= arr.shape[0]
i = 0
for num in range(l):
    arr[num] = 10;
    i += 1
print(arr)
print(i)

[[10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10.]]
9


In [49]:
l= arr.shape[0]
for num in range(l):
    arr[num] = num * 2;
print(arr)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [ 6.  6.  6.  6.  6.  6.  6.  6.  6.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  8.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [14. 14. 14. 14. 14. 14. 14. 14. 14.]
 [16. 16. 16. 16. 16. 16. 16. 16. 16.]]


In [50]:
arr[3:7, 2:7]

array([[ 6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12.]])

In [51]:
# Specific Elements (Fancy indexing)
arr[[1, 5, 7]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14.]])

In [53]:
# reshape
arr = np.arange(45).reshape(9,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [55]:
arr_t = arr.T
arr_t

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44]])

In [56]:
np.dot(arr_t, arr)

array([[5100, 5280, 5460, 5640, 5820],
       [5280, 5469, 5658, 5847, 6036],
       [5460, 5658, 5856, 6054, 6252],
       [5640, 5847, 6054, 6261, 6468],
       [5820, 6036, 6252, 6468, 6684]])

In [60]:
arr_3d = np.arange(90).reshape(2, 5, 9)
arr_3d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44]],

       [[45, 46, 47, 48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59, 60, 61, 62],
        [63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80],
        [81, 82, 83, 84, 85, 86, 87, 88, 89]]])

In [61]:
arr_3d[:1, :3, ::2]

array([[[ 0,  2,  4,  6,  8],
        [ 9, 11, 13, 15, 17],
        [18, 20, 22, 24, 26]]])

In [71]:
# swapaxes
arr = np.array([1, 2, 3])

In [70]:
arr.swapaxes(0,1)

AxisError: axis2: axis 1 is out of bounds for array of dimension 1