# Cole Weber
## Week 12 - 4/6/2021
### Numpy Functions Cont.

In [5]:
import numpy as np
arr1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
arr2 = np.array([[4, 9, 7, 4],[8, 0, 9, 8]])
cond = np.array([[True, False, True, True],[False, False, True, False]])

In [9]:
arr = np.where(cond, arr1, arr2)
arr

array([[1, 9, 3, 4],
       [8, 0, 7, 8]])

In [15]:
from numpy.random import randn
arr = randn(5,5)
arr2 = randn(5, 5)
arr

array([[-0.87124764, -0.3809382 , -0.11102228, -0.88677231,  0.40447164],
       [-1.52845102, -0.36590996, -0.43981928, -0.24820057, -0.17653451],
       [ 0.87024379,  0.95446441, -1.03871861,  0.65887406, -0.27554475],
       [-0.52533065, -1.66214355,  0.16774042, -0.43608618, -0.76646457],
       [ 0.01624981,  0.35823442, -0.50190346,  0.73976704,  0.02777995]])

In [14]:
np.where(arr < 0, 0, arr)

array([[0.        , 0.        , 0.        , 0.        , 0.58059669],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.09512379, 0.44082414, 0.        , 0.74260312, 0.        ],
       [0.        , 0.        , 1.0543428 , 0.        , 0.        ],
       [0.09888205, 1.17634033, 0.28950427, 0.        , 0.29074537]])

In [16]:
np.add(arr, arr2)

array([[-2.17200696, -0.74027983,  0.52148615, -1.23406105, -0.694786  ],
       [-2.39397528,  0.61371263, -1.11710844,  0.95194483, -0.75540005],
       [ 0.79254402,  1.47914034, -2.18539654,  1.63811612,  0.54030818],
       [-0.61161347, -1.3377813 ,  0.07236405, -1.93740103,  0.58856222],
       [-0.24233336,  0.29801012, -0.82572474,  0.86678905,  0.27088033]])

In [19]:
arr_b = [True, False, True, True]
print(np.any(arr_b))
print(np.all(arr_b))

True
False


In [21]:
fruits = np.array(["Apple", "Grapes", "Orange", "Cherry", "Kiwi", "Grapes", "Orange"])
np.unique(fruits)

array(['Apple', 'Cherry', 'Grapes', 'Kiwi', 'Orange'], dtype='<U6')

In [23]:
np.in1d(["Cherry", "Banana", "Grape"], fruits)

array([ True, False, False])

In [27]:
arr = np.arange(1, 11)
arr_2d = arr.reshape(2, 5)
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
# arithmetic methods
arr_2d.sum()

55

In [30]:
arr_2d.sum(0)

array([ 7,  9, 11, 13, 15])

In [31]:
arr_2d.sum(1)

array([15, 40])

In [34]:
print(np.sum(arr_2d, axis = None))
print(np.sum(arr_2d, axis = 0))

55
[ 7  9 11 13 15]


In [35]:
arr.mean()

5.5

In [40]:
arr_2d.mean(1)

array([3., 8.])

In [43]:
arr_2d.var()

8.25

In [44]:
arr_2d.var(0)

array([6.25, 6.25, 6.25, 6.25, 6.25])

In [46]:
arr = np.array([1, 3, 6, 5, 8, 7, 9, 1, 2, 3, 4, 2])
arr.sort()
arr

array([1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9])

In [49]:
i = np.eye(2, 2)
arr = np.array([[-1, 2], [3, 5]])
r = arr * i
r

array([[-1.,  0.],
       [ 0.,  5.]])

In [50]:
m = np.mat([[-1, 2], [3, 5]])
m

matrix([[-1,  2],
        [ 3,  5]])

In [51]:
m * i

matrix([[-1.,  2.],
        [ 3.,  5.]])

In [57]:
# Transpose
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print("_____________")

t = arr.T
t

[[1 2 3 4]
 [5 6 7 8]]
_____________


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [59]:
arr.transpose(0,1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
arr.transpose(1,0)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [65]:
arr_3d = np.arange(1,21).reshape(2,5,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


In [66]:
arr_3d.transpose(1,0,2)

array([[[ 1,  2],
        [11, 12]],

       [[ 3,  4],
        [13, 14]],

       [[ 5,  6],
        [15, 16]],

       [[ 7,  8],
        [17, 18]],

       [[ 9, 10],
        [19, 20]]])

In [75]:
from numpy.random import randn
arr_random = randn(5, 5)
arr_random

array([[-0.08712881,  0.10124748,  2.52650339, -0.58912948, -0.40656664],
       [-1.32781511, -0.69335771,  0.7855722 , -0.48222661, -0.27259598],
       [ 0.25366424,  0.15911733,  0.64489646,  0.928482  , -0.90654932],
       [ 0.38351429, -0.08307969,  0.73876476,  2.41677181,  0.06020378],
       [-0.29678492, -1.48596823, -0.26885167,  0.36709249, -0.49449388]])

In [76]:
randn(5)

array([-0.6373639 , -0.00264027, -0.35610241, -0.46063294,  0.83779428])

In [77]:
np.random.randint(10, 20)

18