# Cole Weber
## Week 10 - 3/26/2021
### Python - Numpy Array Processing

In [3]:
import numpy as np

In [4]:
my_list = np.array([1, 2, 3, 4])

print(my_list.dtype)

int32


In [7]:
fruits = ["Apple", "Orange", "Grape"]
fruit_list =np.array([fruits])
print(fruit_list.dtype)

<U6


In [9]:
number_array = np.array([11, 22, 33, 44], dtype = "S")
print(number_array.dtype)

|S2


In [12]:
my_arr = np.array(['1', '2', 'c', '4'], dtype = "i")
print(my_arr.dtype)

ValueError: invalid literal for int() with base 10: 'c'

In [13]:
float_arr = np.array([10.5, 11.6, 17.8, 20.3])

In [14]:
arr = float_arr.astype("i")

In [15]:
print(arr)

[10 11 17 20]


In [16]:
arr = np.array([1, 0, 0, 1, 0, 1, 3, 4, 2])
print(arr.dtype)
arr2 = arr.astype(bool)
print(arr2)

int32
[ True False False  True False  True  True  True  True]


In [20]:
list1 = [1, 3, 4, 2]
list2 = [7, 6, 3, 9]
two_list = [list1, list2]
two_array = np.array(two_list)
print(two_array)
print(two_array.ndim)

[[1 3 4 2]
 [7 6 3 9]]
2


In [22]:
# numpy built-in fucntions to generate arrays from existing arrays copy() and view()
# copy() is independent. view() is connected both ways
arr1 = np.array([1, 4, 5, 3])
arr1_copy = arr1.copy()
print(arr1)
print(arr1_copy)

[1 4 5 3]
[1 4 5 3]


In [23]:
arr[1] = 5
print(arr1)
print(arr1_copy)

[1 4 5 3]
[1 4 5 3]


In [26]:
arr1_view = arr1.view()
print(arr1)
print(arr1_view)

[1 4 5 3]
[1 4 5 3]


In [27]:
arr1[0] = 20
print(arr1)
print(arr1_view)

[20  4  5  3]
[20  4  5  3]


In [28]:
arr1_view[2] = 9
print(arr1)
print(arr1_view)

[20  4  9  3]
[20  4  9  3]


In [29]:
print(arr1_copy.base)
print(arr1_view.base)

None
[20  4  9  3]


In [32]:
# shape gives the number of elements in each dimension
list1 = [1, 3, 4, 2]
list2 = [7, 6, 3, 9]
two_list = [list1, list2]
two_array = np.array(two_list)
print(two_array.ndim)
print(two_array.shape)

2
(2, 4)


In [35]:
arr = np.array(list1, ndmin = 4)
print(arr)
print(arr.shape)

[[[[1 3 4 2]]]]
(1, 1, 1, 4)
