# Cole Weber
## Week 10 - 3/24/2021
### Pyhton - Numpy

In [61]:
import numpy as np

In [62]:
np.__version__

'1.18.5'

In [63]:
arr = np.array([1, 34, 20, 19, 71])

In [64]:
arr

array([ 1, 34, 20, 19, 71])

In [65]:
type(arr)

numpy.ndarray

In [66]:
#0-D array
arr2 = np.array(1)
print(arr2)

1


In [87]:
#1-D Array
arr3 = np.array([1, 2, 4, 5, 4, 10, 3, 5, 4])
print(arr3[2])
print(arr3.ndim)

4
1


In [92]:
#2-D Array. Known as a Matrix/Table
arr4 = np.array([ [1, 4, 5, 8, 7], [3, 0, 9, 6, 4] ])
print(arr4.ndim)

2


In [98]:
#3-D Array has multiple matrices/2D Arrays
arr5 = np.array([ [[1, 4, 5, 4 ,7],[3, 0, 9, 5, 9]], [[1, 4, 5, 2, 3],[3, 0, 9, 1, 4]] ])
print(arr5[1][0][2])

5


In [70]:
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)
print(arr5.ndim)

0
1
1
3


In [71]:
print(arr4[1][0])

3


In [72]:
print(arr4[1][-1])

4


In [73]:
print(arr5[1,0, -1])

5


In [74]:
dimarray = np.array([1, 2, 3, 4], ndmin = 5)

In [75]:
print(dimarray.ndim)

5


In [76]:
# slicing np arrays. Has to be assigned to a new element. 
# [start:end:step] - Start default is zero, end default is the end of the list, step default is one
print(arr3[1:4])

[2 4 5]


In [77]:
print(arr3[:4])

[1 2 4 5]


In [78]:
# slice from index three to index one from the end
print(arr3[-3:-1])

[3 5]


In [79]:
print(arr3[1:7:2])

[ 2  5 10]


In [80]:
print(arr4)

[list([1, 4, 5, 8, 7]) list([3, 0, 9, 6, 4]) list([2, 3, 5, 7])]


In [95]:
print(arr4.ndim)
print(arr4)

2
[[1 4 5 8 7]
 [3 0 9 6 4]]


In [94]:
print(arr4[1, 0:3])

[3 0 9]


In [99]:
print(arr5)

[[[1 4 5 4 7]
  [3 0 9 5 9]]

 [[1 4 5 2 3]
  [3 0 9 1 4]]]


In [100]:
print(arr5[1, 0:])

[[1 4 5 2 3]
 [3 0 9 1 4]]


In [101]:
print(arr5[1, 0, 1:])

[4 5 2 3]


In [105]:
print(arr5[:, 1, 4])

[9 4]
